### PR TITLE
Upgrade to Node.js v6

### PR DESCRIPTION
**Pull request by catto**
This PR upgrades the build and the runtime container to Node.js v6. (#25)
It seems that there is no incompatible api use. I confirmed that all the tests were successful with Node.js v6.3.0.

### CODE REVIEW

**Comment by stjohnjohnson** [comment]
👍  Woot! 
do_you_even_lift__bro

**Comment by nkatzman** [comment]
The wercker build didn't run. We should validate that the tests work before we merge

**Comment by catto** [comment]
Hmm.. I pushed another commit (just `commit --amend`) but it seems that the wercker build doesn't run.

**Comment by stjohnjohnson** [comment]
Looks like wercker doesn't run for PRs, it runs for branches.  What?!

**Comment by stjohnjohnson** [comment]
@nkatzman I verified that the test ran locally fine in v6 👍 continues

**Comment by nkatzman** [comment]
👍

**Pull request merged**
